### ISSUE TITLE
Fix js dependencies

### ISSUE THREAD

**Issue by subzero79** [nicjo814/openmediavault-docker-gui#1]
Hi nicj814,  good to hear you're back into code
this is the inspector from chrome,

![screen shot 2015-08-13 at 8 15 00 am](https://cloud.githubusercontent.com/assets/7058119/9238199/db60fcce-4193-11e5-9a28-ee5f540f9082.png)

You need to also add the vectorized svg icon for the node

**Comment by subzero79** [comment]
Ok. I've added to ContainerGrid.js the following in the header of the file

// require("js/omv/workspace/grid/Panel.js")
// require("js/omv/data/Store.js")
// require("js/omv/data/Model.js")
// require("js/omv/data/proxy/Rpc.js")

Now is running, you're still missing the icon
BTW looks terrific this plugin. Excelent work, exactly how i imagined.

**Comment by nicjo814** [comment]
Thanks for finding the missing requirements! Regarding the icon I haven't found any good one. I want a whale since that's the logo for docker but have settled for a simple fish icon for now :-)

Glad you like the plugin. I'll try to have it move to the plugin github, but I need some help with that,,,

**Comment by subzero79** [comment]
I tried to scale and bw the whale the other day, but for some reason inkscape wouldn't run in my OS X install. I'll try in a VM maybe with windows. 

On Thu, Aug 13, 2015 at 12:59 AM -0700, "Niclas Berglind" notifications@github.com wrote:

Thanks for finding the missing requirements! Regarding the icon I haven't found any good one. I want a whale since that's the logo for docker but have settled for a simple fish icon for now :-)

Glad you like the plugin. I'll try to have it move to the plugin github, but I need some help with that,,,

**Comment by nicjo814** [comment]
Let me know if you come up with a nice icon :-)

**Comment by nicjo814** [comment]
I've added a proper new icon now so I'll close this issue.
